#+title: dtache.el - Changelog
#+author: Niklas Eklund
#+language: en

* Development

- Add integration with the =consult= package through =dtache-consult.el=.
- Add support for =eshell= through the =dtache-eshell= package.
- macOS (monitor) support is added to the package.

* Version 0.2 (2021-12-23)

- With the recent improvements to =dtache-open-session=, the package is ready to harmonize the user interface. This means deprecating =dtache-list-sessions=.
- Remove external dependency to =embark=. The package now implements an action map that can be used with/without embark.
- Remove external dependency to =marginalia=. The package now provides annotations for all users.
- Fix error in =dtache-env= usage. The integration wasn't correct which resulted in =dtache= failing to execute some commands properly
- Make =dtache-env= optional rather than required. =Dtache= should be fine without it, just that automatic status labeling will not be run

* Version 0.1 (2021-12-15)

- Initial release
