#!/usr/bin/env bash

# detached-env is a script which purpose is to run a detached command, and
# issue to stdout, based on the exit code.

detached_command="$*"

if eval "$detached_command"; then
    echo -e "\nDetached session finished"
else
    echo -e "\nDetached session exited abnormally with code $?"
fi
